# Generated by Django 5.2.1 on 2025-06-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['name'], 'permissions': [('manage_own_playlists', 'Can create/edit/delete own playlists'), ('view_recommendations', 'Can view recommendations')]},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['artist', 'title']},
        ),
    ]
