# Generated by Django 5.2.1 on 2025-06-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-score'], 'permissions': []},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='generated_at',
        ),
    ]
